---
#tasks file for roles/nexus
- name: yum update
  yum:
    name: '*'
    state: latest

- name: install wget and java
  yum: 
    name:
    - wget
    - java-1.8.0-openjdk.x86_64 
    state: latest
 
# - name: make dir 
#   command: mkdir /app 
- name: create a directory called app
  file:
    path: /app
    state: directory
    mode: '0755'

- name: download the latest nexus
  command: wget -O /app/nexus.tar.gz https://download.sonatype.com/nexus/3/latest-unix.tar.gz

# - name: Untar the downloaded file
#   command: tar -xvf /home/ec2-user/app/nexus.tar.gz

- name: Untar the downloaded file
  unarchive:
    src: /app/nexus.tar.gz
    dest: /app
    remote_src: yes # to unpack an archive which already exists on the target.

- name: rename untar nexus-version to  
  command: sudo mv /app/nexus-3.47.1-01 /app/nexus

- name:   create a new user named nexus
  command: sudo adduser nexus

- name: change the ownership of nexus files and nexus data directory to nexus user.
  command: sudo chown -R nexus:nexus /app/nexus

- name: change the ownership of nexus files and nexus data directory to nexus user.
  command: sudo chown -R nexus:nexus /app/sonatype-work


- name: Uncomment run_as_user
  lineinfile: 
    dest: /app/nexus/bin/nexus.rc
    regexp: "^#" 
    line: run_as_user="nexus"
    state: present

- name: copy file nexus.service
  copy: 
    src: nexus.service
    dest: /etc/systemd/system/

- name: add nexus service to boot
  command: sudo chkconfig nexus on

- name: restart nexus
  service: 
    name: nexus
    state: restarted